### PR TITLE
Add Individual README for subfolders

### PR DESCRIPTION
**Pull request by akshay-s-770**

### CODE REVIEW

**Comment by akshay-s-770** [comment]
#48

**Comment by vyasriday** [comment]
Please resolve conflicts.

**Comment by akshay-s-770** [comment]
@vyasriday i have fixed the conflicts

**Comment by vyasriday** [comment]
@akshay-s-770 It would be great if in addition to link to each folder you can also provide a link to the corresponding blog as the folders are anyway visible in the folder. Linking them doesn't make much sense without links to the blogs.

**Comment by vyasriday** [comment]
closing due to no activity on this.

**Pull request closed without merging**
